## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "maracuya-1"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Wim van der Ham"
    title = "Maracuya IT"
    description = "R and statistics"
    authorimage = "/img/logo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id" 

## Social Accounts
[params.social]
    github = "https://github.com/wfjvdham"
    linkedin = "https://www.linkedin.com/in/wim-van-der-ham-8b6a5b44/"
    twitter = "https://twitter.com/wim_vanderham"
    email = "wfjvdham@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/post/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
